import type { Metadata } from "next";
import { ThemeModeScript } from 'flowbite-react';
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import { ToastContainer } from 'react-toastify';
import { Lato } from 'next/font/google';
 

const lato = Lato({
  subsets: ["latin"],  
  weight: ['400', '700'],
  
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning className={lato.className}>
      <head><ThemeModeScript /></head>
      <body        
        style={{ fontFamily: 'Lato, sans-serif' }}
      >
        {children}
        <ToastContainer position="top-right"
          autoClose={3000}          
          hideProgressBar={false}
          newestOnTop
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light" />
      </body>
    </html>
  );
}
